### PR TITLE
VCR tests

### PR DESCRIPTION
**Pull request by thomsbg**
Include the VCR gem, and use it to isolate tests from the live YouTube API

### CODE REVIEW

**Comment by thomsbg** [comment]
For these tests to run successfully, the `GreedyChainIO#read` w/0 arguments bug fix (#59) must be included.

**Comment by kylejginavan** [comment]
What happens with these cached calls if there is a change in the API?

**Comment by thomsbg** [comment]
If there is a change in the API, then the tests will continue to pass. However, you may periodically run the test suite with VCR configured to re-record all http requests to refresh against the live API:

``` ruby
# test/helper.rb

VCR.configure do |c|
  c.default_cassette_options = { :record => :all }
end
```

**Comment by apeckham** [comment]
As a potential contributor it'd be awesome to have VCR tests on this project, because the current suite takes 94 seconds on my machine. If VCR makes that much faster, it'll be easier to contribute. Thank you!

**Comment by yaauie** [comment]
+1 from here. 114s on my last full test run

**Comment by kylejginavan** [comment]
Do you boys know if VCR works with http://travis-ci.org/?  We are trying to set this up now... and that might be the deal that convinces me to use VCR.

**Comment by yaauie** [comment]
I don't see why not.

**Comment by jarthod** [comment]
VCR would be great, i'm also doing a lot of fixes for the tests to be more robust, because they are actually very random because of youtube API caching. They also are totally thread unsafe, running 2 tests on Travis (for 2 ruby versions for example) is impossible since they are acting on the same real youtube account.

**Comment by kylejginavan** [comment]
Yeah, unfortunately things got busy again and I didn't quite get to adding VCR.  This merge no longer goes in smooth and I was hoping to sort it all out but ran out of time.  If you are able to get VCR in/Tom's stuff working and this sucker running on Travis that would be a HUGE contribution.

**Comment by jarthod** [comment]
I've added comment reply feature in my fork, and i'm working on improving the tests right now. When I get something stable on travis i'll do a pull request ;)
I can't dive into VCR integration now because i don't know how it works and I do not have too much free time ^^

**Comment by jarthod** [comment]
Ok I finally added VCR to my branch, I counldn't work without it ^^
I also added comment deletion feature, it's passing: [Build Status](http://travis-ci.org/dimelo/youtube_it)
I'll do a pull request soon ;)

**Comment by kylejginavan** [comment]
That is amazing.  Big win for this project.  I can't wait to merge it.

**Comment by kylejginavan** [comment]
Used a different pull request.

**Comment by chebyte** [comment]
nice jobs thanks!

**Pull request closed without merging**
