### PR TITLE
Support for restriction parameter in video search

### PR DESCRIPTION
**Pull request by egze**
Support for the restriction parameter in search queries.

http://code.google.com/intl/de-DE/apis/youtube/2.0/reference.html#restrictionsp

### CODE REVIEW

**Comment by alecnmk** [comment]
hi,

please, clarify how to get restriction attribute for specific video acquired by id

thanks

**Comment by alecnmk** [comment]
e.g. video hNoS2BU6bbQ is not supported for embedding on certain sites, while 'state' is telling that it's 'published' and just that

**Comment by yaauie** [comment]
@alecnmk it looks like you're confusing the [restriction](http://code.google.com/apis/youtube/2.0/reference.html#restrictionsp) query parameter with the [accessControl](http://code.google.com/apis/youtube/2.0/reference.html#youtube_data_api_tag_yt:accessControl) attributes (currently unsupported by youtube_it, though you're welcome to add it :) ).

The video in question, though, appears not to have an embed restriction, at least for an unauthenticated request originating in the USA:
`GET feeds/api/videos/hNoS2BU6bbQ`

``` xml
<!--SNIP-->
  <yt:accessControl action="comment" permission="allowed" />
  <yt:accessControl action="commentVote" permission="allowed" />
  <yt:accessControl action="videoRespond" permission="moderated" />
  <yt:accessControl action="rate" permission="allowed" />
  <yt:accessControl action="embed" permission="allowed" />
  <yt:accessControl action="list" permission="allowed" />
  <yt:accessControl action="autoPlay" permission="allowed" />
  <yt:accessControl action="syndicate" permission="allowed" />
<!--/SNIP-->
```

**Comment by alecnmk** [comment]
@yaauie thanks, but it won't help.. that param is useless to me now. I was trying to filter out monetized and restricted (in any way) videos, because they are not available on iOS and causing errors in iframe embed player. And that's very frustrating for users. 
I found that having that params won't help after 2 hours of reading through Youtube API Google Groups threads. Long story short, Youtube just don't want you to _know_ what videos are monetized or restricted from playback :)

**Pull request merged**
