### PR TITLE
Upgrade Youtube API to version 2.1  (Fixes subscription issues)

### PR DESCRIPTION
**Pull request by pivotal-bedrocket**
We bumped the api version in the header, then ensured all the tests were green again by removing the cassettes.

### CODE REVIEW

**Comment by chebyte** [comment]
hi therem I have a question, why you need pry gem?

**Comment by pivotal-bedrocket** [comment]
we don't need it, but it was useful for debugging

**Comment by KieranP** [comment]
Why was this closed? It doesn't appear to have been merged in...

**Comment by kylejginavan** [comment]
The merge wasn't clean, because there was a bunch of changes made by the time I got around to merging it.  Therefore, I took the good parts via a manual merge.

**Pull request closed without merging**
