### PR TITLE
Fix comments api

### PR DESCRIPTION
**Pull request by sbounmy**
fix add / delete comments
related ticket : https://github.com/kylejginavan/youtube_it/issues/196

### CODE REVIEW

**Comment by kylejginavan** [comment]
Please fix the build and I can merge this.

**Comment by sbounmy** [comment]
spec is now green locally, not sure why it failed on travis...
I also removed comment reply, it seems to not be supported anymore by youtube API, I had :

``` ruby
Video comment replies are no longer supported: CommentReplyInsertException
```

**Comment by kylejginavan** [comment]
What version of ruby are you using?

**Comment by sbounmy** [comment]
my specs are running against ruby 1.9.3p194

**Comment by jeff-savin** [comment]
Would love to have this fix. Any ETA on when the SSL version of the comments can be merged in?

**Comment by sbounmy** [comment]
screwed up this PR with bad merge sorry. here is a cleaner PR : https://github.com/kylejginavan/youtube_it/pull/230

**Pull request closed without merging**
