### PR TITLE
Youtube Captions API integeration

### PR DESCRIPTION
**Pull request by nazarhussain**
Hi, 

I embedded Youtube Captions API (https://developers.google.com/youtube/2.0/developers_guide_protocol_captions) which was needed for one of my project.

The `captions_update` methods can be used to add new or update existing captions. This is the current options that are supported for this methods.

``` ruby
{
   :language => 'en-US',
    :slug => ''"
}
```

Its signature is `captions_update(video_id,data,opts)` where as data is the content of captions file which can easily be get from `File.read`.

In future, I will embed other features of captions as well and send you the pull requests. 

Thanks.

### CODE REVIEW

**Comment by nazarhussain** [comment]
To clarify one point if any caption for provided `:language` already exists it will be updated  otherwise it will be added as new caption.

**Comment by karlseguin** [comment]
+1

**Comment by cviedmai** [comment]
+1

**Comment by ehoch** [comment]
Any shot you could add in the ability to fetch captions as well?

**Comment by nazarhussain** [comment]
A bit busy these days. Will integrate Captions fetching and other captions related stuff in few weeks.

**Pull request merged**
