### PR TITLE
upgrade nokogiri to 1.6.0

### PR DESCRIPTION
**Pull request by zhu1230**
Upgraded to 1.6.0 of nokogiri for the compatible problem with other gems....
I have run the test suite for this, all passed.

### CODE REVIEW

**Comment by jschroeder9000** [comment]
Looks like there is at least one other issue opened for this (#179).

For me this causes a conflict with the carrierwave_direct gem.

**Comment by iloveitaly** [comment]
:+1:

**Comment by kylejginavan** [comment]
Would it be ok to loosen to use 1.6.x?

**Comment by kylejginavan** [comment]
I'm going to just close this PR and bump to 1.6.X

**Comment by zhu1230** [comment]
@kylejginavan 
I think the json dependency confused many people, which used to use 1.8+ , now, we are again bounded to 1.7+ . this means we have to downgrade the json gem to use youtube_it 2.4.0.

**Pull request closed without merging**
