### PR TITLE
OAuth2Client refresh token is blank when refreshing

### PR DESCRIPTION
**Pull request by masterkain**
Hello,
I'm using something like this:

``` ruby
      ::YouTubeIt::OAuth2Client.new({
        client_token_expires_at: @youtube_credentials.expires_at,
        client_access_token:     @youtube_credentials.token,
        client_refresh_token:    @youtube_credentials.refresh_token,
        client_id:               Settings.services.youtube.client_key,
        client_secret:           Settings.services.youtube.client_secret,
        dev_key:                 Settings.services.youtube.developer_key,
      })
```

I save this data in order to properly refresh the token when it does expire (it does so by raising a OAuth2::Error).

It should be noted that I'm using `client_token_expires_at` because I think that the proposed `expires_at` in readme is wrong, this pull request should fix this.

When I refresh the token through `client.refresh_access_token!` what I have back is an instance of `OAuth2::AccessToken` which does indeed contain a new `token` but the `refresh_token` is nil.

I need the refresh_token stored somewhere in order to refresh the old one at the next authentication error.
I'm still not sure if this AccessToken should carry the refresh_token but I can't see other ways to perform a refresh afterwards.

Thanks.

```
[1] pry(#<OAuth2::AccessToken>)> ls
OAuth2::AccessToken#methods: []  client  delete  expired?  expires?  expires_at  expires_in  get  options  options=  params  post  put  refresh!  refresh_token  request  token
self.methods: __binding_impl__
instance variables: @client  @expires_at  @expires_in  @options  @params  @refresh_token  @token
locals: _  _dir_  _ex_  _file_  _in_  _out_  _pry_
[2] pry(#<OAuth2::AccessToken>)> expired?
=> false
[3] pry(#<OAuth2::AccessToken>)> expires?
=> true
[4] pry(#<OAuth2::AccessToken>)> expires_in
=> 3600
[5] pry(#<OAuth2::AccessToken>)> refresh_token
=> nil
[10] pry(#<OAuth2::AccessToken>)> refresh!
RuntimeError: A refresh_token is not available
```

### CODE REVIEW

**Comment by masterkain** [comment]
Added pry session

**Comment by yaauie** [comment]
The original token – the one with the `refresh_token` – is a special-sauce token in that it has the capability of creating bearer tokens. Some implementations of OAuth2 allow these bearer tokens to be generated in chain (e.g., the refreshed token contains a refresh_token of its own), while others (e.g., Google) do not. 

Because this is specific to the auth-provider, and because this gem only uses one provider, perhaps something like this would suffice, although it breaks the transparency of having a 1:1 mapping with OAuth2:

``` diff
    def refresh_access_token!
-     new_access_token = access_token.refresh! 
+     @original_access_token ||= @access_token 
+     new_access_token = @original_access_token.refresh!
      require 'thread' unless Thread.respond_to?(:exclusive)
      Thread.exclusive do
        @access_token = new_access_token
        @client = nil
      end
      @access_token
    end
```

_The above code has not been tested in any way._

**Comment by masterkain** [comment]
Thanks @yaauie,
I see what you did there, but it is still unclear to me what's the supposed way to deal with access tokens, once they expire, in youtube_it. I mean, are you asking your users to re-authenticate every so often?

My requirement is to have enough up to date info in database to perform a refresh without stressing too much the end user and forcing him to re-authenticate every x hours. I'll try to fork and apply the patch above.

Thanks!

**Comment by masterkain** [comment]
Putting this here http://code.google.com/p/google-api-ruby-client/issues/detail?id=12&sort=-id as a note

**Comment by masterkain** [comment]
I was a little lost but upon inspecting OAuth2 I got it working.

**Pull request closed without merging**
